In [6]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
df = pd.read_csv("data/heart.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

### سوال 37

میانگین تمام ویژگی‌های عددی را برای دو کلاس target مقایسه کنید.

In [10]:
df.groupby("target")[["age","trestbps","chol","thalach","oldpeak"]].mean()

              age    trestbps        chol     thalach   oldpeak
target
0       56.601449  134.398551  251.086957  139.101449  1.585507
1       52.496970  129.303030  242.230303  158.466667  0.583030

با توجه به این جدول کسایی که بیماری قلبی ندارند سن بیشتری دارند(میانگین سن:56 سال)وهمچنین فشارخون و کلسترول و شیت سی تی بالا تری دارند ولی ضربان قلب ناشی از ورزششون کمتر هستش

اما کسانی که بیماری قلبی دارند ضربان قلب هنگام تستشون بالاتره که امکان داره یکی از دلایل مراجعشون همین باشه